name: Build And Publish Search Index

on:
  push:
    branches:
      - main

jobs:
  build-publish-search-index:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - name: Publish algolia search index
        env:
          ALGOLIA_WRITE_KEY: ${{ secrets.LIT_DEV_ALGOLIA_WRITE_KEY }}
        run: bun run publish-search-index
