name: Unit tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - run: bun install
      - run: bun run test:unit
      - run: bun run test:generated-api
